name: 24-6
favicon: null
layout_spectrum: 0.7125755113083869
typography_spectrum: 0.9006740017794073
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.19109446206130087
  lightness: 0.5250455429777503
  saturation: 0.5178751165512949
  rhythmicContrast: 0.3052438588347286
purpose: []
